#!/usr/bin/env python3

import xlrd
import codecs
import sys
from pupa.scrape import Person


def process(xls_file):
    with open(xls_file, 'rb') as fd:
        book = xlrd.open_workbook(file_contents=fd.read())
        for sheet in book.sheets():
            yield (sheet, handle_sheet(sheet))


def handle_sheet(sheet):
    for lrow in iter([sheet.row(x) for x in range(sheet.nrows)]):
        header, *row = (x.value for x in lrow)
        if header == "":
            continue
        yield (header, row)


for sheet, stream in process(*sys.argv[1:]):
    data = dict(stream)
    jurisdiction_name = sheet.name
    if jurisdiction_name in [
        'Applications, Documents',
    ]:
        continue

    ignore = [
        'Age Requirement',
        'Links to Applications / Documents',
        'Residency Requirements',
        'Paid / Unpaid - Salary',
        'Position Duration',
        'Date of Next Election & Application Deadline',
        'Professional Requirement',
        'Position Level',
        'Filing Fees',
        'County',
        'Position Description / Responsibilities',
        'Address of Where to Send App.',
        codecs.encode('qre43rj4', 'rot13'),
    ]
    for x in ignore:
        if x in data:
            data.pop(x)

    print(jurisdiction_name)

    if 'Current Position Holder' in data:
        persons = data.pop('Current Position Holder')
        districts = data.pop('District / Jurisdiction')
        titles = data.pop('Position Title')
        for person, district, title in zip(persons, districts, titles):
            # print(person, title)
            pass

    assert data == {}, data.keys()
