#!/usr/bin/env python3

import xlrd
import sys


def process(xls_file):
    with open(xls_file, 'rb') as fd:
        book = xlrd.open_workbook(file_contents=fd.read())
        for sheet in book.sheets():
            yield (sheet, handle_sheet(sheet))


def handle_sheet(sheet):
    rows = iter([sheet.row(x) for x in range(sheet.nrows)])
    for row in rows:
        yield [x.value for x in row]


for sheet, stream in process(*sys.argv[1:]):
    pass
